#format can be "text" or "json" for different output (human or machine readable)
#format: 'text'
#checkAsserts checks assertions
checkAsserts: true
#seqLen defines how many transactions are in a test sequence
seqLen: 200
#testLimit is the number of test sequences to run
testLimit: 1000000
#estimateGas makes echidna perform analysis of maximum gas costs for functions (experimental)
estimateGas: true
#directory to save the corpus; by default is disabled
corpusDir: 'corpus'
#deployer is address of the contract deployer (who often is privileged owner, etc.)
deployer: '0x41414141'
#sender is set of addresses transactions may originate from
sender: ['0x42424242', '0x43434343']
